### ISSUE TITLE
Замечания по паттерну "Стратегия" (функциональная версия)

### ISSUE THREAD

**Issue by alexey-malov** [dervesp/ood2017#1]
- [x] Уткам передавать объекты функций (по конст. ссылке)

- [x] Для создания нужных стратегий полета или танцев лучше завести соотв. Make-функции. Передавать результат вызова этих функций

**Comment by dervesp** [comment]
>  Уткам передавать объекты функций (по конст. ссылке)
>
> Для создания нужных стратегий полета или танцев лучше завести соотв. Make-функции. Передавать результат вызова этих функций
замечания исправлены
